# Generated by Django 5.2.7 on 2025-11-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='id',
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
