# Generated by Django 5.2.7 on 2025-11-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breshop', '0002_remove_contact_id_alter_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
