# Generated by Django 5.2.7 on 2025-11-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breshop', '0003_remove_tag_id_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brecho',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='brecho',
            name='instagram',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='brecho',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
