# Generated by Django 5.2.7 on 2025-11-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breshop', '0004_brecho_email_brecho_instagram_brecho_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brecho',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
