# Generated by Django 5.2.7 on 2025-11-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breshop', '0005_alter_brecho_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='brecho',
            old_name='adress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='adress',
            new_name='address',
        ),
    ]
