# Generated by Django 5.2.7 on 2025-11-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breshop', '0006_rename_adress_address_rename_adress_brecho_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Product',
        ),
    ]
